import data from "../../public/data.json"; //import json data
import React, { useMemo, useState } from "react";
import Head from "next/head";
import Header from "../../components/roadmap/Header";
import ProgressBar from "../../components/roadmap/ProgressBar";
import { capitalizeFirstLetter } from "../../components/utils/capitalize";
import CardRoadmap from "../../components/UI/CardRoadmap";

function Roadmap() {
  const [filterRoadmap, setFilterRoadmap] = useState("In-Progress");
  const [reqPlanned, setReqPlanned] = useState([]);
  const [reqProgress, setReqProgress] = useState([]);
  const [reqLive, setReqLive] = useState([]);

  useMemo(() => {
    const requests = data.productRequests;
    const planned = requests.filter((item) => item.status === "planned");
    const progress = requests.filter((item) => item.status === "in-progress");
    const live = requests.filter((item) => item.status === "live");
    setReqPlanned(planned);
    setReqProgress(progress);
    setReqLive(live);
  }, [data]);

  return (
    <div>
      <Head>
        <title>Product Feedback - Roadmap</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/assets/favicon-32x32.png' />
      </Head>
      <Header />
      <ProgressBar
        filterRoadmap={filterRoadmap}
        setFilterRoadmap={setFilterRoadmap}
        reqPlanned={reqPlanned}
        reqProgress={reqProgress}
        reqLive={reqLive}
      />

      <section className='mx-6'>
        <div className='my-6'>
          <h3 className='mb-1 text-lightnavy'>
            {capitalizeFirstLetter(filterRoadmap)} (
            {filterRoadmap === "In-Progress" && reqProgress.length}
            {filterRoadmap === "Planned" && reqPlanned.length}
            {filterRoadmap === "Live" && reqLive.length})
          </h3>
          <p className='body3 font-normal text-gray'>
            {filterRoadmap === "In-Progress" && `Currently being developed`}
            {filterRoadmap === "Planned" && `Ideas prioritzed for research`}
            {filterRoadmap === "Live" && `Released features`}
          </p>
        </div>
        <ul className='mb-[98px] space-y-4'>
          {filterRoadmap === "Planned" &&
            reqPlanned.map((item, i) => (
              <CardRoadmap
                key={i}
                itemData={item}
                filterRoadmap={filterRoadmap}
              />
            ))}
          {filterRoadmap === "In-Progress" &&
            reqProgress.map((item, i) => (
              <CardRoadmap
                key={i}
                itemData={item}
                filterRoadmap={filterRoadmap}
              />
            ))}
          {filterRoadmap === "Live" &&
            reqLive.map((item, i) => (
              <CardRoadmap
                key={i}
                itemData={item}
                filterRoadmap={filterRoadmap}
              />
            ))}
        </ul>
      </section>
    </div>
  );
}

export default Roadmap;
