import React, { useState } from "react";
import Head from "next/head";
import Header from "../components/suggestions/Header";
import MobileMenu from "../components/suggestions/MobileMenu";
import SortBar from "../components/suggestions/SortBar";
import CardSuggestions from "../components/UI/CardSuggestions";

//import json data
import data from "../public/data.json";

export default function Home() {
  const [mobMenuOpen, setMobMenuOpen] = useState(false);
  const [filterMenuOpen, setFilterMenuOpen] = useState(false);

  return (
    <div className='relative flex h-screen flex-col'>
      <Head>
        <title>Product Feedback</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/assets/favicon-32x32.png' />
      </Head>
      <MobileMenu mobMenuOpen={mobMenuOpen} setMobMenuOpen={setMobMenuOpen} />

      <Header mobMenuOpen={mobMenuOpen} setMobMenuOpen={setMobMenuOpen} />
      <SortBar
        filterMenuOpen={filterMenuOpen}
        setFilterMenuOpen={setFilterMenuOpen}
      />

      <main className='bg-lightgray'>
        <ul className='mx-6 mt-8 mb-14 space-y-4'>
          {data.productRequests.map((product) => (
            <li key={product.id}>
              <CardSuggestions productData={product} />
            </li>
          ))}
        </ul>
      </main>

      <div
        className='flex-1 bg-lightgray'
        onClick={() => setFilterMenuOpen(false)}
      ></div>
    </div>
  );
}
