import data from "../public/data.json"; //import json data
import React, { useState, useMemo, useEffect } from "react";
import Head from "next/head";
import MobileHeader from "../components/suggestions/MobileHeader";
import MobileMenu from "../components/suggestions/MobileMenu";
import SortBar from "../components/suggestions/SortBar";
import CardSuggestions from "../components/UI/CardSuggestions";
import NoFeedback from "../components/suggestions/NoFeedback";
import { sortRequests } from "../components/utils/sort";
import DesktopTabletHeader from "../components/suggestions/DesktopTabletHeader";

export default function Home() {
  const [mobMenuOpen, setMobMenuOpen] = useState(false);
  const [filterMenuOpen, setFilterMenuOpen] = useState(false);
  const [filterSelect, setFilterSelect] = useState("Most Upvotes");
  const [categorySelect, setCategorySelect] = useState("all");
  const [roadmapCount, setRoadmapCount] = useState();

  const sortedRequests = useMemo(() => {
    const input = data.productRequests;
    return sortRequests(input, filterSelect, categorySelect);
  }, [filterSelect, categorySelect]);

  useEffect(() => {
    var countPlanned = data.productRequests.filter(
      (item) => item.status === "planned"
    ).length;
    var countProgress = data.productRequests.filter(
      (item) => item.status === "in-progress"
    ).length;
    var countLive = data.productRequests.filter(
      (item) => item.status === "live"
    ).length;

    setRoadmapCount({
      countPlanned,
      countProgress,
      countLive,
    });
  }, [setRoadmapCount]);

  return (
    <div className='flex flex-col lg:mx-auto lg:max-w-[1190px] lg:px-10'>
      <Head>
        <title>Product Feedback</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/assets/favicon-32x32.png' />
      </Head>

      <MobileMenu
        mobMenuOpen={mobMenuOpen}
        setMobMenuOpen={setMobMenuOpen}
        categorySelect={categorySelect}
        setCategorySelect={setCategorySelect}
        roadmapCount={roadmapCount}
      />

      <MobileHeader mobMenuOpen={mobMenuOpen} setMobMenuOpen={setMobMenuOpen} />

      <div className='lg:mt-[94px] lg:flex '>
        <DesktopTabletHeader
          mobMenuOpen={mobMenuOpen}
          setMobMenuOpen={setMobMenuOpen}
          categorySelect={categorySelect}
          setCategorySelect={setCategorySelect}
          roadmapCount={roadmapCount}
        />
        <div className='lg:inline-block lg:flex-1'>
          <SortBar
            filterMenuOpen={filterMenuOpen}
            setFilterMenuOpen={setFilterMenuOpen}
            filterSelect={filterSelect}
            setFilterSelect={setFilterSelect}
            sortedRequests={sortedRequests}
          />

          <main className='' onClick={() => setFilterMenuOpen(false)}>
            <ul className='mx-6 mt-8 mb-14 space-y-4 md:mx-10 md:mt-6 md:mb-[120px] lg:mx-0 lg:mt-6 lg:max-w-[825px] lg:space-y-5'>
              {sortedRequests.length === 0 ? (
                <NoFeedback />
              ) : (
                sortedRequests.map((product) => (
                  <li key={product.id}>
                    <CardSuggestions productData={product} />
                  </li>
                ))
              )}
            </ul>
          </main>
        </div>
      </div>
    </div>
  );
}
