import React from "react";
import Head from "next/head";
import CardSuggestions from "../../components/UI/CardSuggestions";
import Comments from "../../components/feedback/Comments";
import Header from "../../components/feedback/Header";
import AddComment from "../../components/feedback/AddComment";
import LoadingSpinner from "../../components/UI/LoadingSpinner";
import { useRouter } from "next/router";

//GRAPHQL
import { useQuery } from "@apollo/client";
import { GET_FEEDBACK_BY_ID } from "../../graphql/queries";

function Detail() {
  const router = useRouter();

  const { data, error, loading } = useQuery(GET_FEEDBACK_BY_ID, {
    variables: {
      id: router.query.detailId,
    },
  });

  const productRequest = data?.getFeedback;

  return (
    <section className='relative mx-auto mt-6 mb-[88px] h-full max-w-[810px] px-6 md:mt-14 md:mb-[120px] md:px-10 lg:mb-[130px] lg:mt-[94px]'>
      <Head>
        <title>Product Feedback</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/assets/favicon-32x32.png' />
      </Head>
      <Header />
      {loading ? (
        <div className='mt-[56px] flex justify-center md:mt-[70px]  lg:mt-[105px]'>
          <LoadingSpinner />
        </div>
      ) : (
        <>
          <CardSuggestions productData={productRequest} />
          <Comments productData={productRequest} />
          <AddComment productData={productRequest} />
        </>
      )}
    </section>
  );
}

export default Detail;
